### ISSUE TITLE
Ensure the freedom of all users

### ISSUE THREAD

**Issue by 2mac** [17bitHero/feels#3]
I recommend using a different license for your code.

If you're like me and want all users to have freedom, I recommend the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.txt). Then, as it states at the bottom of the text, you should include a copyright and license declaration at the top of your source code.

If you'd like to see an example of this, check out [one of my projects which does this](https://github.com/delwink/coinfetch).

**Comment by 17bitHero** [comment]
Thanks, I changed the license.

**Comment by 2mac** [comment]
You changed the header of your source to use the AGPL, but the LICENSE file is just the regular GPL.
